### ISSUE TITLE
Next track will not play automatically

### ISSUE THREAD

**Issue by thetwom** [gateship-one/odyssey#72] opened 2017-06-02 19:34 UTC
I have got the problem, that when playing a track, the next track in the playlist won't start automatically. Rather I have to press "play" to go on. 
This happens in all occasions (player active on the screen, player in the background, using internal speakers, using bluetooth speakers, I also tried switching of the battery optimization for odyssee).
My system is a Fairphone 2 with Android 6.0.1.

I should also note, that I tried also some other players and some have a similar issue, others not.

**Comment by gnome17** [comment] 2017-06-12 18:05
Hi,
I am sorry to dissapoint you but it seems that the media player of your device causes this problem. We'll think you have similar problems with players that use the system media player and other players like vlc which uses their own playback framework will work.

Since we have no device with a similar issue we will not be able to help you.

**Comment by djselbeck** [comment] 2017-06-29 08:42
Closing this as we have no way to reproduce this.

**Closed by djselbeck** 2017-06-29 08:42 UTC
