### ISSUE TITLE
Doesn't respond to headset controls after long pause

### ISSUE THREAD

**Issue by LoneFenris** [gateship-one/odyssey#40] opened 2017-01-05 19:57 UTC
When paused for too long, Odyssey removes its notification and doesn't respond to headset controls until the app is re-opened. Ideally, one should be able to resume playback in Odyssey (if it was the last active music player) just by using the headset controls. Android 7.1.1.

**Comment by djselbeck** [comment] 2017-01-05 20:15
Thanks for reporting this.

This is actual the intended behaviour. The application waits 5 minutes and then terminates the background services because we think that it is unlikely that the user wants to resume after this period of time from background controls because it is likely the user stopped listening to music.

5 minutes proofed to be a good time to get into a coffee shop and get a cup of coffee to go.

**Comment by LoneFenris** [comment] 2017-01-05 20:27
I see. It may not address use cases such as primarily listening to music in the car during commutes or even just out running errands. But if that's the intended behavior, I won't press the issue.

**Comment by dkanada** [comment] 2017-04-24 21:59
Any chance you would be open to adding a setting for this? If I had the option I would just have a persistent notification for music control, I am using this app all the time. A checkbox preference to set the notification to persistent would be amazing, but a dialog to select different times would also be great.

**Comment by gnome17** [comment] 2017-06-12 18:15
Since this is not a bug and we have no intention to change this behaviour I will close this issue.

**Closed by gnome17** 2017-06-12 18:15 UTC
