### ISSUE TITLE
Albums with the same name by different artists are grouped together

### ISSUE THREAD

**Issue by nfisher1226** [gateship-one/odyssey#220] opened 2021-06-30 16:39 UTC
# Bug Report

**Comment by nfisher1226** [comment] 2021-06-30 16:45
Affects both Play Store and F-Droid versions of Odyssey. When I start in Artist view and select an album to play, if there is another album in my collection by a different artist but with the same album title, the tracks of the two different albums will play intermingled together. 

Example:
Playing "Lotus" by Soen plays track one from "Lotus" by Santana, followed by track one of "Lotus" by Soen, so on and so forth. 

Especially problematic if one has multiple "Greatest Hits" compilations by different artists.

**Comment by gnome17** [comment] 2021-06-30 17:15
Thanks for reporting it. 

I can confirm your observation. Definitely not what we had in mind.

As a workaround you could access the album via the integrated filebrowser. That should still work.

For future bug reports please use our template and don't enter the text as a comment afterwards ;)

**Comment by gnome17** [comment] 2021-06-30 17:34
Which android version are you using?

**Comment by nfisher1226** [comment] 2021-06-30 18:54
Running Android 11, kernel 4.14.113

Sorry for the bug report ettiquette. Hopefully I won't be filing more bugs.

**Comment by gnome17** [comment] 2021-07-01 18:44
We are certain now it is android 11 related issue.

If you want we could provide you an apk with a workaround until we have a proper fix in place.

**Comment by nfisher1226** [comment] 2021-07-03 16:21
If a fix is in the works, I'll just sit tight and watch this bug report. Of course, if you need testers I would be glad to volunteer.

**Comment by gnome17** [comment] 2021-08-01 17:51
A quick status update:
We are currently in the final testing stages of a hopefully proper fix for this issue.

After that we will prepare a new release.

**Comment by gnome17** [comment] 2021-08-23 19:05
So finally we released a new version that should fix the issue you discovered.

Should be available via the Play Store within the next ours and should be available via FDroid within a week or so.

Many thanks for reporting the issue :)

I will close the issue now. If the issue is still present after the update feel free to reopen the Issue again.

**Closed by gnome17** 2021-08-23 19:05 UTC
Labels: bug

**Comment by Saroumane** [comment] 2021-09-02 10:30
Hello, just updated to 1.2.0 via Fdroid, I see no fix here.
![IMG_20210902_122702](https://user-images.githubusercontent.com/22261137/131828266-1798f9cf-0512-40a7-ac74-e7b2ecc8183b.jpg)
(Android 11 on Pixel 3a)

**Comment by gnome17** [comment] 2021-09-02 10:44
As you already pointed out this is another issue. Please create a new issue or update an existing one and add as many details as you could. Thanks.
