### ISSUE TITLE
Files that have ”:" in name can't be played

### ISSUE THREAD

**Issue by licaon-kter** [gateship-one/odyssey#7] opened 2016-10-21 08:06 UTC
[Vanilla](https://github.com/vanilla-music/vanilla) can play the same WAV file though.

It opens the file, it sees it time length at least.

**Comment by gnome17** [comment] 2016-10-21 19:29
We cannot reproduce this issue. If you want you can send us your WAV file per mail torschiffeins@gmail.com

**Comment by licaon-kter** [comment] 2016-10-21 22:50
It's actually one from [Echo](https://github.com/mafik/echo)

**Comment by licaon-kter** [comment] 2016-10-22 07:41
So the problem is elsewhere, in the way Echo names the files, by including the time as `xx:xx`, where that `:` will make Odyssey not play that file.

**Comment by djselbeck** [comment] 2016-10-22 15:57
We can confirm this issue. Unfortunately it looks like it is a bug in the mediaplayer of android. Google play (which also uses the stock MediaPlayer api) does also not play the songs. 

In logcat you can see that there is an permission denied error on the file. 

VLC is able to play the file because it brings its own playback engine which for use at the moment is out of scope. Also using the android mediaplayer brings the benefit of hardware accelerated playback.

Sadly at the moment we don't see any solution other than using a different name schema. Does it needs to be : (: tend to be very problematic on vfat formatted sdcards anyway :) )

**Comment by licaon-kter** [comment] 2016-10-22 19:10
Yes, but VFAT would not allow that in the name in the first place.

You can just pop-up a dialogue stating why this can be played and maybe offer a rename field or something?

**Comment by adrian-bl** [comment] 2016-10-23 16:59
The root cause of this issue is that the MediaPlayer framework tries to parse the path as an URI if it contains a ':' char.

So you either need to pass an URI to it (eg: file://...) or open the file on your own and pass the FD to the MediaPlayer class.

We fixed this issue in VanillaMusic with this commit: https://github.com/vanilla-music/vanilla/commit/939c59fe71d10c1034e130c62f96541fd91ac6bb

**Comment by djselbeck** [comment] 2016-10-23 17:18
Thanks for the tip, this is cool. We'll integrate this :)

**Comment by djselbeck** [comment] 2016-10-24 19:05
Thanks again for the work on this issue to both of you. We just commited the release tag for the version that fixes the issue. t

Also we will now use the track duration from the file to show if it is not part of the media database. 

We'll close the issue now.

**Closed by djselbeck** 2016-10-24 19:05 UTC
