### ISSUE TITLE
Colons in filenames cause crash

### ISSUE THREAD

**Issue by bamonroe** [gateship-one/odyssey#167] opened 2018-10-01 08:46 UTC
If a music file has a colon in the filename, the app crashes if you try to play it. It also crashes when opening, even to view, an m3u playlist if the playlist contains a file with a colon in the filename.

Changing the name of the file fixes the issue, even if the colon remains in the title metadata. Maybe the application takes the colon to reference an external filesystem? Otherwise filename character escaping might just need to include a colon?

I really enjoy this app, I've been using it daily for a few months. Thanks for all your hard work!

App Version from FDROID, 1.1.15
Lineage OS, 14.1
Android 7.1.2

**Comment by gnome17** [comment] 2018-10-03 14:14
Hi,
thanks for reporting this issue. The cause of the crash should already be fixed in the master branch. But we cannot play files containing a colon. Do you have any player that is able to do that?

Currently we are not sure why these files are not playable, so maybe it will be easier if you just rename those files. In my opinion a file with a colon in the filename is not really a good idea.

**Comment by bamonroe** [comment] 2018-10-03 15:00
That sounds great, any idea when a version with the fix will be available in Fdriod? I'd prefer to not have to install the APK directly.

I agree, colons in filenames are not great, but some artists / podcasts put colons in the names of the titles of songs/episodes, so they inevitably end up in the filenames.  

There are lots of music players that can play files that have colon in their name, I'm not sure what the technical limitation of parsing out special characters from a file name would be:
* The default music player that ships with Lineage OS
* Music-Player: https://github.com/MaxFour/Music-Player
* Simple-Music-Player: https://github.com/SimpleMobileTools/Simple-Music-Player
* Vanilla Music: https://github.com/vanilla-music/vanilla

There are other's I'm sure, these are just the ones that worked as I went down the list of music players in Fdroid. I prefer the UI in Odyssey and how it handles relative-path playlists, so I'd really rather continue using it rather than switching to something else if this can be fixed.

**Comment by gnome17** [comment] 2018-10-06 10:45
Hi,

currently I am not sure when we will release a new version. The issue that files with colons are not playable still remains and until now I have no clue how to fix the issue properly. Before we release a new version I would like to resolve all issues first.

So in any case don't expect a quick solution it will take at least some more weeks. Until then your only option is to rename the files, sorry about that. But in my opinion it doesn't make sense to just release the crash fix, because you won't be able to play the files without any information what is going wrong.

The mentioned commit has nothing to do with the issue that a file is not playable but thanks for your suggestion.

By the way it is really nice to hear that somebody else is using the playlist features of odyssey :-)

**Comment by bamonroe** [comment] 2018-10-06 13:08
Thanks for the reply.

No problem about  the timing to the next release, it makes sense to wait until you've got all the other issues squashed. I'll just have to write a script to replace colons with hyphens or something until this bug is squashed - not a huge deal. 

The playlist feature significantly improves my day. I sync podcasts from my laptop to my Nextcloud and then to my phone. The relative path playlist means I can use the same playlist file from my laptop on my phone, so I can just continue playing the next podcast when I leave in the morning. It's great! I'm surprised how many music players out there don't support relative path playlists like Odyssey. 

Thanks for all the hard work!

**Comment by gnome17** [comment] 2018-11-10 11:11
Hi,
thanks for your kind words ;)

Our testing is finally done and we just released a new version that should handle filenames with colons properly.

Should be already available via google play and should be avaible at fdroid in the next week I guess.

If you still encounter issues with such files please open another issue but I hope it should be fine now :-)

**Closed by gnome17** 2018-11-10 11:11 UTC
Labels: bug

**Comment by bamonroe** [comment] 2018-11-10 11:35
Just downloaded the update, works like a charm. Thanks so much for your effort!
