### ISSUE TITLE
Odyssey loses state when closed

### ISSUE THREAD

**Issue by ildar** [gateship-one/odyssey#113] opened 2018-01-07 08:19 UTC
That's seen evidently as the tracks in queue are those I listened some time before, not the latest.
This happens at OOM situation which is the part of Android world, sorry.
I think that Odyssey should take extra care of it:
1. Save state on Pause
2. and if played for more then 5 or 10 minutes

**Comment by djselbeck** [comment] 2018-01-08 21:55
Yes you are right. Actually Odyssey saves it state if you swipe the notification away (in pause state) or after 5 Minutes. The problem is that with the migration to android 8 api we are not running for this long. 

We'll fix this

**Comment by gnome17** [comment] 2018-02-03 20:09
Hi,
we released a new version that should address your problem. Could you please give us feedback if this release solved your problem?

**Comment by dennisguse** [comment] 2018-02-07 20:29
Seems to work (LineageOS 7.1, Odyssey 1.1.11 via Fdroid).
1. Play
2. Pause
3. Go to home screen
4. Swipe away notification
5. Open Odyssey
-> exact position and repeat state is restored

However, on killing the app (force stop via task manager - similar to OOM) does not restore the latest state, but the previous one is restored.

**Comment by djselbeck** [comment] 2018-02-07 20:31
OOM kills are SIGKILL terminations. There is nothing Odyssey can do, thats the definition of kill.

Android usually does not use SIGKILL for termination operations but gracefully terminates services.

also 1.1.11 is not the newest version

**Comment by dennisguse** [comment] 2018-02-07 21:36
@djselbeck Sorry, I was expecting Fdroid to be up to date and did not verify it.
My mistake.

**Comment by djselbeck** [comment] 2018-02-07 21:38
They automatically follow the tagged releases on github and then build it from source. Which is nice, because this way applications are guaranteed to match the provided source code.

Today version 1.1.12 landed it f-droid ;)

**Comment by A-UNDERSCORE-D** [comment] 2024-06-15 16:44
This appears to have reappeared in 1.3.0

**Comment by gnome17** [comment] 2024-06-18 14:26
I doubt it reappeared because it was never truly gone ;)

We released a new version 1.3.1 that makes the state save logic more robust and will additionally save every time the playback stops. We think this should be enough but feel free to create a new issue if you think it is still an issue.

Please keep in mind that although we released already it might take a couple of days until the version is available to you (depending if you are using fdroid or the google play store).

**Closed by gnome17** 2024-06-18 14:26 UTC
Labels: bug

**Comment by A-UNDERSCORE-D** [comment] 2024-06-18 17:15
Understood, and thanks! I thought it was gone as I hadn't had state issues previously. thanks for all the work Odyssey!
